### ISSUE TITLE
PageRepository override not working with TYPO3 10.4

### ISSUE THREAD

**Issue by x4e-salvi** [lochmueller/custom_shortcut#1]
https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/10.0/Deprecation-88746-PageRepositoryPHPClassMovedFromFrontendToCoreExtension.html

page/tt_content shortcuts are broken in HMENU objects after the execution of the included migration wizard.
Tested with TYPO3 10.4.16.

I think it's related to:
https://forge.typo3.org/issues/91237

**Comment by lochmueller** [comment]
Hey @x4e-salvi 
thanks for reporting. I added a version check in ext_localconf.php and create a v10 overwrite for the one class and the hook. I don't check this directly and will test this in the next days...
Regards,
Tim

**Comment by lochmueller** [comment]
Checked in current master. Works... will release a new version in a few seconds.
