### ISSUE TITLE
Fatal Error after install

### ISSUE THREAD

**Issue by prathers** [lochmueller/custom_shortcut#10]
I get this after `composer req lochmueller/custom-shortcut`

`NOTICE: PHP message: PHP Fatal error:  Declaration of HDNET\CustomShortcut\Overrides\PageRepository10::getPageShortcut($shortcutFieldValue, $shortcutMode, $thisUid, $iteration = 20, $pageLog = [], $disableGroupCheck = false) must be compatible with TYPO3\CMS\Core\Domain\Repository\PageRepository::getPageShortcut($shortcutFieldValue, $shortcutMode, $thisUid, $iteration = 20, $pageLog = [], $disableGroupCheck = false, bool $resolveRandomPageShortcuts = true) in /var/www/html/private/typo3conf/ext/custom_shortcut/Classes/Overrides/PageRepository10.php on line 1`

DDEV

TYPO3 v11

PHP v8.0

**Comment by lochmueller** [comment]
Hey @prathers ,

Already fixed in current master... https://github.com/lochmueller/custom_shortcut/commit/bf6a36fabf11b6b1002337e489233a9c90b107f4

Regards,
Tim

**Comment by prathers** [comment]
Thx Tim, 
But if I do a `ddev composer req lochmueller/custom-shortcut` I don't get the latest `main` AFAIS?

Best,
Preben

**Comment by lochmueller** [comment]
Yes @prathers Currently, you can run "composer req lochmueller/cotsom-shortcut:dev-main".

**Comment by prathers** [comment]
Perfect THANKS
