### ISSUE TITLE
Additional parameters?

### ISSUE THREAD

**Issue by klodeckl** [lochmueller/custom_shortcut#11]
Hi, I would like to add query parameters to the target page link like https://github.com/smichaelsen/typo3-shortcut-params. Would you integrate a field for that?

**Comment by klodeckl** [comment]
Hi @lochmueller,
thank you, sounds great. :)
In my case I would like to add news overwriteDemand categories parameter.
Regard, Bernhard

**Comment by lochmueller** [comment]
Sorry... no progress here. I will close this issue. Perhaps this will be relevant in the future.
