### ISSUE TITLE
Directly accessing shortcut page results in error

### ISSUE THREAD

**Issue by chesio** [lochmueller/custom_shortcut#4]
Hi,

I noticed that when an URL of a shortcut page with custom shortcut is accessed directly, TYPO3 throws an `1301648167 TYPO3\CMS\Core\Error\Http\ServiceUnavailableException` error with message _"The requested page didn't have a proper connection to the tree-root!"_.

I would expect that instead TYPO3 makes 307 redirect to target URL (as in case of standard shortcuts).

This happens in TYPO3 9.5, I haven't tested it with 10.4.

**Comment by chesio** [comment]
Hi Tim,

sorry for replying so late, but I finally have time to look into this issue again.

Version 0.9.4 didn't fix the problem for me, but in the meantime I got to upgrade the website in question to TYPO3 10.4. After the upgrade I found out that commit a9b4fe1d1242592dc188fc57216de429a22da81a actually broke the functionality for any custom shortcuts (= other than `tt_content`). It seems the LinkHandler is not invoked anymore, because the resolved page UID does not have the `shortcut://` scheme anymore. If I revert this change, custom shortcuts work again. The original issue ("The requested page didn't have a proper connection to the tree-root!") is still present though.

Cheers,
Česlav

**Comment by chesio** [comment]
Btw. you were right, the commit a9b4fe1d1242592dc188fc57216de429a22da81a fixes the original issue. Unfortunately only for `tt_content` shortcuts while also completely breaking shortcut functionality for custom (Extbase) shortcuts.

**Comment by lochmueller** [comment]
I reopen the issue and will check this in the near future.

**Comment by lochmueller** [comment]
Fixed with a new middleware in current master and next release.
