### ISSUE TITLE
Fatal Error on install (use in ext_localconf.php)

### ISSUE THREAD

**Issue by eBornstein** [lochmueller/custom_shortcut#6]
Hi,
I get the following error message when I install the extension.
Fatal error: Cannot use TYPO3\CMS\Core\Utility\GeneralUtility as GeneralUtility because the name is already in use...

If I read it correctly on the web, "use" is only allowed in ext_localconf.php as of TYPO3 11. Can you please fix this?

cutsom_shortcut 0.9.4
TYPO3 10.4.24
PHP 7.3.23

**Comment by lochmueller** [comment]
Hey @eBornstein is already fixed and part of the next release: https://github.com/lochmueller/custom_shortcut/commit/d3bbb5d44b1fe4265766977781b85575f1638653
