### ISSUE TITLE
Typo3  11 Compatibility

### ISSUE THREAD

**Issue by SOFTWORK** [lochmueller/custom_shortcut#7]
Is there a way, to get this useful extension Typo3 11 ready. I need the functionality to link from page shortcut to pages with anchor points. I find out, that in Typo3 11 there is no $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_content.php']['typolinkLinkHandler'] function - it was removed.
Is there any other solution to get this working?

**Comment by lochmueller** [comment]
Hey @SOFTWORK 
I think the extension have to migrate to the newer API to get TYPO3 v11 support: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.4/Deprecation-90937-VariousHooksInContentObjectRenderer.html
I will keep the issue open... I will check this in the next weeks.
Regards,
Tim

**Comment by lochmueller** [comment]
Hey @SOFTWORK 
pushed Version 1.0.1 to TER.
Ticket closed,
Tim

**Comment by SOFTWORK** [comment]
Hi Tim,

thanks for upgrading this extension - but I have trouble to use it. I get this error: 
Class "HDNET\CustomShortcut\Shortcut\Content" not found

Thanks for your help.

**Comment by lochmueller** [comment]
The class exists: https://github.com/lochmueller/custom_shortcut/blob/main/Classes/Shortcut/Content.php
You are not using composer, right? I have no Dev system without composer, so I cannot reproduce this.
I add https://github.com/lochmueller/custom_shortcut/commit/6e374892c1e31eb4d204a4556d639b6a75cdd088 and push 1.0.2 to TER. Perhaps this solve the problem. If not... feel free to create a new issue (Do not forget... TYPO3 Version, Extension Version, Composer yes/no)
Regards,
Tim

**Comment by SOFTWORK** [comment]
Thanks for updating the extension, yes - this is a installation without composer. We use Typo3 - V11, now we have the following error.
Fatal error: Declaration of HDNET\CustomShortcut\Overrides\PageRepository10::getPageShortcut($shortcutFieldValue, $shortcutMode, $thisUid, $iteration = 20, $pageLog = [], $disableGroupCheck = false) must be compatible with TYPO3\CMS\Core\Domain\Repository\PageRepository::getPageShortcut($shortcutFieldValue, $shortcutMode, $thisUid, $iteration = 20, $pageLog = [], $disableGroupCheck = false, bool $resolveRandomPageShortcuts = true) in /typo3conf/ext/custom_shortcut/Classes/Overrides/PageRepository10.php on line 15

**Comment by lochmueller** [comment]
Hey @SOFTWORK Fixed in current master. Please create new issues for more findings.

Regards,
Tim
