### ISSUE TITLE
Fatal error after installation

### ISSUE THREAD

**Issue by KreativeKrise** [lochmueller/custom_shortcut#8]
I have 2 TYPO3 installations. 1 locally for testing and 1 on a server.

Locally everything runs fine, but on the server I get the following error if I install custom_shortcut:

`Fatal error: Class TYPO3\CMS\Core\Http\SelfEmittableLazyOpenStream may not inherit from final class (GuzzleHttp\Psr7\LazyOpenStream) in /var/www/vhosts/domain.tld/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/SelfEmittableLazyOpenStream.php on line 29`

Do you have any idea what could cause this issue?

**Comment by lochmueller** [comment]
Hey @KreativeKrise 
Could you send me same feedback, which TYPO3 Version and if you are using composer mode? 
Regards,
Tim

**Comment by lochmueller** [comment]
Hey... I think this is a Core Problem that is already solved. For the future I suggest to install TYPO3 in composer mode...
https://forge.typo3.org/issues/94454
https://forge.typo3.org/projects/typo3cms-core/repository/1749/revisions/a0f9a59209e68ca2388c2705e93185ff8a6560df

I will close this issue.

Regards,
Tim
